// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetStream(ctx context.Context, id pgtype.UUID) (GetStreamRow, error)
	ListStreams(ctx context.Context) ([]ListStreamsRow, error)
	UpdateStream(ctx context.Context, arg UpdateStreamParams) (UpdateStreamRow, error)
}

var _ Querier = (*Queries)(nil)
